language: cpp
sudo: required

script:
 - "bash -ex .travis-ci.sh"

addons:
  apt:
    packages: &base_pkg
      #base packages for all builds
      - gdb
      - libasound2-dev 
      - libusb-dev 
      - libftdi-dev 
      - shared-mime-info 
      - libudev-dev 
      - libmad0-dev 
      - libsndfile1-dev
      - libfftw3-dev
    packages: &qt5_pkg
      - *base_pkg
      - qt56-meta-minimal
      - qt56script
      - qt56multimedia
      - qt56serialport
      - g++-5
    packages: &qt5_qml
      - *base_pkg
      - qt59-meta-minimal
      - qt59declarative
      - qt59quickcontrols2
      - qt593d
      - qt59gamepad
      - qt59svg
      - qt59multimedia
      - libpulse-dev
      - g++-7

matrix:
  fast_finish: true
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      env: TASK='compile' QT='qt4'
      addons:
        apt:
          packages:
           - *base_pkg
           - libqt4-dev
    - os: linux
      dist: trusty
      compiler: gcc
      env: TASK='compile' QT='qt5'
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
           - sourceline: 'ppa:beineri/opt-qt562-trusty'
          packages:
           - *qt5_pkg
    - os: linux
      dist: trusty
      compiler: gcc
      env: TASK='coverage' QT='qt5'
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
           - sourceline: 'ppa:beineri/opt-qt562-trusty'
          packages:
           - *qt5_pkg
           - lcov
    - os: linux
      dist: trusty
      compiler: gcc
      env: TASK='appimage' QT='qt5qml'
      addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
           - sourceline: 'ppa:beineri/opt-qt594-trusty'
          packages:
           - *qt5_qml
cache:
  apt: true

before_install:
 - if [ "$QT" = "qt4" ]; then export QMAKE=qmake; fi
 - if [ "$QT" = "qt5" ]; then export QMAKE=/opt/qt56/bin/qmake; fi
 - if [ "$QT" = "qt5qml" ]; then export QMAKE=/opt/qt59/bin/qmake; fi
 - if [ "$TASK" = "coverage" ]; then gem install coveralls-lcov; fi
#Report the qmake version
 - $QMAKE -v
#Remove the old g++/gcc to ensure we're using the latest ones
 - if [ "$QT" = "qt5" ]; then sudo ln -sf /usr/bin/g++-5 /usr/bin/g++; sudo ln -sf /usr/bin/gcc-5 /usr/bin/gcc; fi
 - if [ "$QT" = "qt5qml" ]; then sudo ln -sf /usr/bin/g++-7 /usr/bin/g++; sudo ln -sf /usr/bin/gcc-7 /usr/bin/gcc; fi
#Report the compiler version
 - $CXX --version
 # Start xvfb so UI tests don't fail
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"

after_success:
 - if [ "$TASK" = "coverage" ]; then coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage/coverage.info; fi
